# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{meta-spotify}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["philnash"]
  s.date = %q{2009-10-30}
  s.description = %q{TODO: longer description of your gem}
  s.email = %q{philnash@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "HISTORY",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/meta-spotify.rb",
     "lib/meta-spotify/album.rb",
     "lib/meta-spotify/artist.rb",
     "lib/meta-spotify/track.rb",
     "meta-spotify.gemspec",
     "test/fixtures/album.xml",
     "test/fixtures/album_search.xml",
     "test/fixtures/artist.xml",
     "test/fixtures/artist_search.xml",
     "test/fixtures/track.xml",
     "test/fixtures/track_search.xml",
     "test/fixtures/track_search_page_2.xml",
     "test/helper.rb",
     "test/test_album.rb",
     "test/test_artist.rb",
     "test/test_track.rb"
  ]
  s.homepage = %q{http://github.com/philnash/meta-spotify}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{A ruby wrapper for the Spotify Metadata API}
  s.test_files = [
    "test/helper.rb",
     "test/test_album.rb",
     "test/test_artist.rb",
     "test/test_track.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
  end
end

